name: Build and Publish .NET Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.401'  # Specify the .NET version you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Publish using DefaultContainer profile
      run: dotnet publish /p:PublishProfile=DefaultContainer

    # Optional: Add other steps, such as deploying the published files or creating a Docker image
    # For example, pushing to a container registry:
    # - name: Docker Login
    #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker Image
    #   run: docker build -t your-image-name:latest .

    # - name: Push Docker Image
    #   run: docker push your-image-name:latest
